#!/usr/bin/env python

import sys
import os
from lib import loader
from lib import logger

from lib.commands import Commands

# init project base dir
BASE_DIR = os.path.dirname((os.path.abspath(__file__)))
sys.path.append(BASE_DIR)
loader.base_dir = BASE_DIR

def main():
    commands = Commands()
    commands.reg()
    commands.main()

if __name__ == '__main__':
    sys.exit(main())
