[project]
name = "library.project.git"
family = "karma-iot"
version = "0.1.0"
maintainer = "tiannian<dtiannian@aliyun.com>"
upstream = "https://github.com/karma-iot/library"
arch = [ "general" ]
platform = [ "general" ]
[init]
folder = [ "src", "include" ]

